#!/usr/bin/env python3

import os
import sys

import helpers

from analyzer import Analyzer
from termcolor import colored

def main():

    # ensure proper usage
    if len(sys.argv) != 2:
        sys.exit("Usage: ./tweets @username")

    # absolute paths to lists
    positives = os.path.join(sys.path[0], "positive-words.txt")
    negatives = os.path.join(sys.path[0], "negative-words.txt")

    # instantiate analyzer
    analyzer = Analyzer(positives, negatives)

    # get list of tweets
    list_of_tweets = helpers.get_user_timeline(sys.argv[1], 50)

    if list_of_tweets is None:
        sys.exit("Account or Tweets not available.")

    for tweet in list_of_tweets:
        score = analyzer.analyze(tweet)
        if score > 0.0:
            print(colored(str(score) + " " + tweet, "green"))
        elif score < 0.0:
            print(colored(str(score) + " " + tweet, "red"))
        else:
            print(colored(str(score) + " " + tweet, "yellow"))

if __name__ == "__main__":
    main()
